openapi: 3.0.1
info:
  title: Blog
  description: 'Blog API'
  version: 1.0.0
servers:
- url: http://localhost:8080
security:
- jwt: []
components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /user:
    post:
      summary: Sign up
      requestBody:
        content:
          application/json:
            schema:
                type: object
                properties:
                  email:
                    type: string
                    format: email
                  password:
                    type: string
      responses:
        200:
          description: User created successfully
  /login:
    get:
      summary: Login
      parameters:
        - name: email
          in: query
          schema:
            type: string
            format: email
        - name: password
          in: query
          schema:
            type: string
            format: password
      responses:
        200:
          description: Logged in successfully
          content:
            application/json:
              schema:
                type: string
        400:
          description: Invalid user/password
  /posts:
    post:
      summary: Create a new post
      requestBody:
        content:
          application/json:
            schema:
                type: object
                properties:
                  title:
                    type: string
                  content:
                    type: string
      responses:
        200:
          description: Post created successfully  
    get:
      summary: Get all posts
      responses:
        200:
          description: List of all posts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title: 
                      type: string
                    content:
                      type: string
  /posts/{id}:
    put:
      summary: Edit a post
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
                type: object
                properties:
                  title:
                    type: string
                  content:
                    type: string
      responses:
        200:
          description: Post edited successfully  
    delete:
      summary: Delete a post
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Post was deleted      
      
    
    