openapi: 3.0.1
info:
  title: Blog
  description: 'Blog API'
  version: 1.0.0
servers:
- url: http://localhost:8080
paths:
  /user:
    post:
      requestBody:
        content:
          application/json:
            schema:
                type: object
                properties:
                  email:
                    type: string
                    format: email
                  password:
                    type: string
      responses:
        200:
          description: User created successfully
  /login:
    get:
      parameters:
        - name: email
          in: query
          schema:
            type: string
            format: email
        - name: password
          in: query
          schema:
            type: string
            format: password
      responses:
        200:
          description: Logged in successfully
          content:
            application/json:
              schema:
                type: string
        400:
          description: Invalid user/password
     
  