version: '3.9'
services: 
    redis:
        image: redis
        ports: 
            - 6380:6379
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        ports:
            - 3307:3306
    adminer:
        image: adminer
        restart: always
        ports:
            - 8090:8080
